name: CI (Windows)

on:
  pull_request: {}
  push: { branches: [ main ] }

permissions:
  contents: read

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}

jobs:
  core-checks:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8.0.302'
          distribution: temurin
      - name: Setup Gradle Build Action
        uses: gradle/gradle-build-action@v2
      - id: Run core tests
        run: |
          ./gradlew clean testcontainers:check --no-daemon --continue

  non-core-checks:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8.0.302'
          distribution: temurin
      - name: Setup Gradle Build Action
        uses: gradle/gradle-build-action@v2
      - id: Run core tests
        run: |
          ./gradlew clean check -x testcontainers:check --no-daemon --continue
